#!/usr/bin/env bash
set -eu

main() {
  certbot --rsa-key-size 4096 --no-bootstrap certonly --manual \
    -d jsx.jp \
    -d *.jsx.jp \
    -d *.secure.jsx.jp \
    -d *.share.jsx.jp \
    -d *.store.jsx.jp \
    -d *.gate.jsx.jp \
    -d *.shop.jsx.jp \
    -d *.cms.jsx.jp \
    -d *.api.jsx.jp \
    -d *.jp.jsx.jp \
    -d *.us.jsx.jp \
    -d *.eu.jsx.jp \
    -d *.fr.jsx.jp \
    -d *.cn.jsx.jp \
    -d *.os.jsx.jp \
    -d *.in.jsx.jp \
    -d *.s.jsx.jp \
    -d *.x.jsx.jp \
    --preferred-challenges dns --register-unsafely-without-email \
    --agree-tos | tee dns-txt
  cd /etc/letsencrypt/live
  zip -r /root/tls *
  echo "Created - $(ls -lh /root/tls.zip)"
}

main
