#!/usr/bin/env bash
set -eu

export PATH=$PATH:/usr/local/bin:$HOME/bin:$HOME/.local/bin

run-cron() {
  LOG_DIR="$(dirname $0)/logs"
  LOG_FILE="$LOG_DIR/cron-certificate_$(date -Iseconds).log"
  mkdir -p $LOG_DIR
  {
    echo "$(TZ=Asia/Tokyo date -Iseconds) === [ Let's Encrypt ] ==="
    cd /home/docker/certbot
    bash run-docker
    FILE=$(find /tmp/root-tls | sort | tail -1)
    ls -l $FILE
    cp $FILE /home/docker/partner/tls.zip

    echo "$(TZ=Asia/Tokyo date -Iseconds) === [ Kubernetes ] ==="
    cd $HOME/_/cloud/k8s/
    . configure
    updateTLSSecret
    echo
  } | tee -a $LOG_FILE 2>&1

  exit
}

main() {
  run-cron
}

main
