#!/usr/bin/env bash
set -eu

run-docker() {
  docker pull ghcr.io/jobscale/certbot
  DNS_CONFIG_FILE=dns-config
  docker run --rm --name certbot \
  -v /tmp/root-tls:/root/tls \
  -e "DNS_CONFIG=$(cat ${DNS_CONFIG_FILE})" \
  -i ghcr.io/jobscale/certbot ./certonly
}

{
  time run-docker
}
